### ISSUE TITLE
BackPorting

### ISSUE THREAD

**Issue by SorosBoy** [Adrenix/OldSwing#1]
Hello , i want to backport this mod to 1.8.9(for personal use) but i dont understand where you get the obsfucated name of 
the method etc i mean `  String UPDATE_EQUIPPED_ITEM = isObfuscated ? "a" : "updateEquippedItem";` how do you get the "a" please ?

**Comment by Adrenix** [comment]
I used bspkrs [MCP Mapping Viewer](https://github.com/bspkrs/MCPMappingViewer) to find what each method/property's obfuscated name was.
