### ISSUE TITLE
1.16.5-2.3.0 causes the player to drop 2 items when pressing the Q key instead of 1 item.

### ISSUE THREAD

**Issue by Thombias** [Adrenix/OldSwing#11]
I have noticed that when dropping items via the vanilla default "Q" key i kept throwing 2 items instead of the usual 1 item per key press. I reverted back to mod version 1.16.5-2.2.3 and the issue is not present there.

Really loving all these new eyecandy additions from mod version 2.3.0 (especially the semi-2D dropped items), so i hope you can fix this little issue! :D

**Comment by Adrenix** [comment]
Thank you for the report! I have fixed the issue and will release a patch very soon. Glad you like the new additions! :)
