### ISSUE TITLE
Incompatible with VanillaFix

### ISSUE THREAD

**Issue by Finnagarf** [Adrenix/OldSwing#12]
Got this crash log a few times tried disabling Foamfix to no avail, then tried disabling VanillaFix and the mod worked properly and all the features I tested worked fine.

---- Minecraft Crash Report ----
// There are four lights!

Time: 2022-04-30 08:17:21 CDT
Description: Initializing game

java.lang.IllegalAccessError: tried to access class org.spongepowered.asm.mixin.transformer.MixinProcessor from class net.minecraftforge.fml.common.Loader
    at net.minecraftforge.fml.common.Loader.handler$zza000$beforeConstructingMods(Loader.java:1141)
    at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:594)
    at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232)
    at net.minecraft.client.Minecraft.init(Minecraft.java:467)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3931)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
    at org.multimc.EntryPoint.listen(EntryPoint.java:143)
    at org.multimc.EntryPoint.main(EntryPoint.java:34)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_331, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 776769408 bytes (740 MB) / 1483735040 bytes (1415 MB) up to 9544663040 bytes (9102 MB)
  JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx10240m
  IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
  FML: MCP 9.42 Powered by Forge 14.23.5.2860 Optifine OptiFine_1.12.2_HD_U_G5 32 mods loaded, 32 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State | ID                  | Version                 | Source                                             | Signature                                |
       |:----- |:------------------- |:----------------------- |:-------------------------------------------------- |:---------------------------------------- |
       | L     | minecraft           | 1.12.2                  | minecraft.jar                                      | None                                     |
       | L     | mcp                 | 9.42                    | minecraft.jar                                      | None                                     |
       | L     | FML                 | 8.0.99.99               | forge-1.12.2-14.23.5.2860-universal.jar            | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | L     | forge               | 14.23.5.2860            | forge-1.12.2-14.23.5.2860-universal.jar            | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | L     | foamfixcore         | 7.7.4                   | minecraft.jar                                      | None                                     |
       | L     | oseca               | 1.2.0                   | OSECA-Forge-1.12.2-1.2.0.jar                       | None                                     |
       | L     | aether_legacy       | 1.5.3.2                 | aether-1.12.2-v1.5.3.2.jar                         | None                                     |
       | L     | aiimprovements      | 0.0.1.3                 | AIImprovements-1.12-0.0.1b3.jar                    | None                                     |
       | L     | antiqueatlas        | 4.6.3                   | antiqueatlas-1.12.2-4.6.3.jar                      | None                                     |
       | L     | antiqueatlasoverlay | 1.2                     | antiqueatlas-1.12.2-4.6.3.jar                      | None                                     |
       | L     | beta_days           | v1.2.2                  | beta_days-1.12.2-1.2.2.jar                         | None                                     |
       | L     | clumps              | 3.1.2                   | Clumps-3.1.2.jar                                   | None                                     |
       | L     | ding                | 1.0.2                   | Ding-1.12.2-1.0.2.jar                              | None                                     |
       | L     | doggytalents        | 1.15.1.6                | DoggyTalents-1.12.2-1.15.1.6.jar                   | None                                     |
       | L     | dynamictrees        | 1.12.2-0.9.27           | DynamicTrees-1.12.2-0.9.27.jar                     | None                                     |
       | L     | enchdesc            | 1.1.20                  | EnchantmentDescriptions-1.12.2-1.1.20.jar          | None                                     |
       | L     | epicsiegemod        | 13.168                  | EpicSiegeMod-13.168.jar                            | None                                     |
       | L     | fastfurnace         | 1.3.1                   | FastFurnace-1.12.2-1.3.1.jar                       | None                                     |
       | L     | foamfix             | 0.10.14-1.12.2          | foamfix-0.10.14-1.12.2.jar                         | None                                     |
       | L     | insomniac           | 1.6                     | insomniac-1.6.jar                                  | None                                     |
       | L     | jei                 | 4.16.1.302              | jei_1.12.2-4.16.1.302.jar                          | None                                     |
       | L     | kleeslabs           | 5.4.12                  | KleeSlabs_1.12.2-5.4.12.jar                        | None                                     |
       | L     | libraryex           | 1.2.2                   | LibraryEx-1.12.2-1.2.2.jar                         | None                                     |
       | L     | mobends             | 1.2.1                   | MoBends_1.12.2-1.2.1-19.12.21.jar                  | None                                     |
       | L     | mousetweaks         | 2.10.1                  | MouseTweaks-2.10.1-mc1.12.2.jar                    | None                                     |
       | L     | mutantbeasts        | 1.12.2-1.0.2            | MutantBeasts-1.12.2-1.0.2.jar                      | None                                     |
       | L     | netherex            | 2.2.5                   | NetherEx-1.12.2-2.2.5.jar                          | None                                     |
       | L     | soundfilters        | 0.12.1_for_1.12         | SoundFilters-0.12.1_for_1.12.jar                   | None                                     |
       | L     | spiderstpo          | 1.0.3                   | spiders-2.0-1.12.2-1.0.3.jar                       | None                                     |
       | L     | vanillafix          | 1.0.10-150              | VanillaFix-1.0.10-150.jar                          | None                                     |
       | L     | structurize         | 1.12.2-0.10.277-RELEASE | structurize-1.12.2-0.10.277-RELEASE.jar            | None                                     |
       | L     | minecolonies        | 1.12.2-0.11.804-RELEASE | minecolonies-1.12.2-0.11.804-RELEASE-universal.jar | None                                     |
  Loaded coremods (and transformers): VanillaFixLoadingPlugin (VanillaFix-1.0.10-150.jar)
                                        
                                      OSECACore (OSECA-Forge-1.12.2-1.2.0.jar)
                                        
                                      Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.14-1.12.2.jar)
                                        pl.asie.foamfix.coremod.FoamFixTransformer
  GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 512.15' Renderer: 'NVIDIA GeForce RTX 3060 Ti/PCIe/SSE2'
  Suspected Mods: Unknown
  Launched Version: MultiMC5
  LWJGL: 2.9.4
  OpenGL: NVIDIA GeForce RTX 3060 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 512.15, NVIDIA Corporation
  GL Caps: Using GL 1.3 multitexturing.
           Using GL 1.3 texture combiners.
           Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
           Shaders are available because OpenGL 2.1 is supported.
           VBOs are available because OpenGL 1.5 is supported.
  Using VBOs: Yes
  Is Modded: Definitely; Client brand changed to 'fml,forge'
  Type: Client (map_client.txt)
  Resource Packs: 
  Current Language: English (US)
  Profiler Position: N/A (disabled)
  CPU: 12x Intel(R) Core(TM) i5-10400 CPU @ 2.90GHz

**Comment by Adrenix** [comment]
Unfortunately there is nothing I can do on my end to fix this issue. This is a problem only the VanillaFix mod can fix. A known solution to this problem is renaming the VanillaFix mod jar in your mods folder by prefixing it with an `a`. For example, the mod's filename should look like this in the mod's folder: `a_VanillaFix-1.0.10-150.jar`. This will make sure the VanillaFix mod will load before mine.

**Comment by Finnagarf** [comment]
> Unfortunately there is nothing I can do on my end to fix this issue. This is a problem only the VanillaFix mod can fix. A known solution to this problem is renaming the VanillaFix mod jar in your mods folder by prefixing it with an `a`. For example, the mod's filename should look like this in the mod's folder: `a_VanillaFix-1.0.10-150.jar`. This will make sure the VanillaFix mod will load before mine.

ah this worked perfectly, thank you for the fix and quick reply
