### ISSUE TITLE
Oldswing crashes on startup when i have optiforge and optifine installed

### ISSUE THREAD

**Issue by brockthefox** [Adrenix/OldSwing#4]
[2021-02-22-1.log](https://github.com/Adrenix/OldSwing/files/6024425/2021-02-22-1.log)

**Comment by Adrenix** [comment]
I'll have to investigate this. For now, if you can play without optifine/optiforge then the mod should work without problem.

**Comment by Adrenix** [comment]
This issue is now fixed in version 2.0.1. You can grab the update from CurseForge.

Thank you for the report!
